/*
 * Copyright 2026 FlowWarden
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.flowwarden.stream;

import org.bson.BsonDocument;
import org.bson.BsonValue;

import java.time.Instant;
import java.util.Map;
import java.util.Optional;

/**
 * Provides access to Change Stream event metadata, documents, and actions.
 *
 * <p>Instances are created by the FlowWarden runtime and passed to handler
 * methods annotated with {@link io.flowwarden.stream.annotation.OnChange @OnChange}
 * (and future typed handlers like {@code @OnInsert}, {@code @OnUpdate}, etc.).</p>
 *
 * @param <T> the document type
 */
public interface ChangeStreamContext<T> {

    // ---- Event metadata ----

    /** Unique event identifier generated by FlowWarden. */
    String getEventId();

    /** Type of the MongoDB operation that triggered this event. */
    OperationType getOperationType();

    /** Name of the stream handler processing this event. */
    String getStreamName();

    /** Source MongoDB collection name. */
    String getCollectionName();

    /** Source MongoDB database name. */
    String getDatabaseName();

    /** MongoDB cluster timestamp of the operation (second precision). */
    Instant getClusterTime();

    /** MongoDB wall-clock time of the operation (millisecond precision, MongoDB 6.0+). Returns {@code null} if unavailable. */
    Instant getWallTime();

    /** MongoDB resume token for this event. */
    BsonDocument getResumeToken();

    /**
     * MongoDB transaction information if this event was emitted as part of a
     * transaction (both {@code lsid} and {@code txnNumber} present), empty
     * otherwise. Useful for handlers that need to group events of the same
     * transaction — audit logs, aggregation, atomicity-preserving downstream
     * propagation.
     */
    Optional<TransactionInfo> getTransactionInfo();

    /** Current retry attempt number (1-based, always 1 until retry is implemented). */
    int getAttemptNumber();

    /** Returns a human-readable summary of this event, suitable for logging. */
    String summary();

    // ---- Document access ----

    /**
     * Returns the full document after the operation, if available.
     *
     * @param type the expected document class
     * @return the document, or empty if not available
     */
    Optional<T> getFullDocument(Class<T> type);

    /**
     * Returns the full document before the operation (MongoDB 6.0+, requires pre-image).
     *
     * @param type the expected document class
     * @return the document before change, or empty if not available
     */
    Optional<T> getFullDocumentBeforeChange(Class<T> type);

    /**
     * Returns the description of updated fields (UPDATE operations only).
     */
    Optional<UpdateDescription> getUpdateDescription();

    /** Returns the document key ({@code _id}) of the affected document. */
    BsonValue getDocumentKey();

    // ---- Actions ----

    /**
     * Manually sends this event to the Dead Letter Queue.
     *
     * @param reason human-readable reason for DLQ routing
     */
    void sendToDlq(String reason);

    /**
     * Immediately persists the current event's token as the processed
     * anchor ({@code lastProcessedToken}) — an <strong>advanced early
     * acknowledgement</strong>.
     *
     * <p>The write happens while the handler is still running: outside an
     * atomic transaction covering the handler's effects, the caller takes
     * responsibility for having completed those effects <em>before</em> the
     * call — if the handler fails afterwards, or the process crashes before
     * it returns, the event will NOT be re-delivered on restart. The
     * automatic terminal-settlement guarantee ("the anchor only advances on
     * settled events") applies to FlowWarden-managed checkpoints, not to
     * this manual override.</p>
     *
     * <p>Only a <em>confirmed</em> write counts: on a store failure the
     * anchor stays dirty (the error is signaled via
     * {@code onCheckpointFailed} without failing the handler) and the
     * automatic policy — count or time threshold — retries it. A successful
     * manual save makes the anchor clean: the automatic thresholds will not
     * rewrite this event's token.</p>
     */
    void saveCheckpointNow();

    /**
     * Attaches custom metadata to this event for downstream processing.
     *
     * @param key   metadata key
     * @param value metadata value
     */
    void addMetadata(String key, Object value);

    /**
     * Retrieves custom metadata by key.
     *
     * @param key  metadata key
     * @param type expected value type
     * @param <V>  value type
     * @return the metadata value, or empty if not present
     */
    <V> Optional<V> getMetadata(String key, Class<V> type);

    /**
     * Returns all custom metadata attached to this event (unmodifiable).
     */
    Map<String, Object> getAllMetadata();
}
